import 'package:flutter/material.dart';
import 'package:lama/features/filter_studio/domain/entities/filter_params.dart';
import 'package:lama/features/filter_studio/presentation/models/filter_studio_style_preset.dart';

class FilterStudioStyleCatalog {
  static final List<FilterStudioStylePreset> presets =
      <FilterStudioStylePreset>[
    ..._buildPack(
      categoryId: 'cinematic',
      categoryEn: 'Cinematic',
      categoryAr: 'سينمائي',
      badgeEn: 'Signature',
      badgeAr: 'توقيع',
      taglineEn: 'Deep contrast, film grain, and composed shadows.',
      taglineAr: 'تباين عميق وحبوب فيلمية وظلال موزونة.',
      icon: Icons.movie_creation_outlined,
      accent: const Color(0xFFFFA26B),
      featuredIndices: const {0, 4, 8},
      namesEn: const [
        'Midnight Frame',
        'Silver Cut',
        'Velvet Drama',
        'Afterglow Reel',
        'Shadow Theater',
        'Film Bloom',
        'Night Harbor',
        'Eclipse Grade',
        'Smoke Scene',
        'Grand Finale',
      ],
      namesAr: const [
        'إطار منتصف الليل',
        'قطع فضي',
        'دراما مخملية',
        'بكرة الشفق',
        'مسرح الظلال',
        'ازدهار الفيلم',
        'مرفأ الليل',
        'تدرج الكسوف',
        'مشهد الدخان',
        'النهاية الكبرى',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.12, 1.28, step),
          saturation: _lerp(0.84, 1.04, step),
          exposure: _lerp(-0.04, 0.08, step),
          brightness: _lerp(-0.02, 0.03, step),
          warmth:
              index < 5 ? _lerp(-0.03, 0.04, step) : _lerp(0.01, 0.07, step),
          tint: _lerp(-0.02, 0.03, step),
          blur: index.isEven ? _lerp(0.4, 1.8, step) : 0.0,
          aura: index % 3 == 0
              ? _lerp(0.14, 0.26, step)
              : _lerp(0.02, 0.08, step),
          auraColor:
              index.isEven ? const Color(0xFFFFB36B) : const Color(0xFF88C8FF),
          grain: _lerp(0.08, 0.20, step),
          scanlines: index % 4 == 0 ? 0.06 : 0.0,
          overlayColor:
              index.isEven ? const Color(0x120B132B) : const Color(0x10FFFFFF),
          cinemaMode: true,
          vignette: _lerp(0.14, 0.28, step),
          lightLeakIndex: index % 3 == 0 ? 1 : 0,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'editorial',
      categoryEn: 'Editorial',
      categoryAr: 'إديتوريال',
      badgeEn: 'Runway',
      badgeAr: 'منصة',
      taglineEn: 'Clean contrast with premium studio polish.',
      taglineAr: 'تباين نظيف مع لمسة استوديو راقية.',
      icon: Icons.auto_fix_high_rounded,
      accent: const Color(0xFF8DE0FF),
      featuredIndices: const {0, 2, 7},
      namesEn: const [
        'Runway Silk',
        'Atelier Soft',
        'Studio Muse',
        'Paper Gloss',
        'Quiet Vogue',
        'Ivory Press',
        'Clean Issue',
        'Form Line',
        'High Society',
        'Gallery Tone',
      ],
      namesAr: const [
        'حرير المنصة',
        'أتيليه ناعم',
        'ملهمة الاستوديو',
        'لمعان الورق',
        'فوغ هادئ',
        'آيفوري برس',
        'إصدار نظيف',
        'خط التكوين',
        'مجتمع راقٍ',
        'نغمة المعرض',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.05, 1.16, step),
          saturation: _lerp(1.00, 1.10, step),
          exposure: _lerp(-0.03, 0.05, step),
          brightness: _lerp(-0.02, 0.02, step),
          warmth:
              index.isEven ? _lerp(-0.01, 0.05, step) : _lerp(0.0, 0.06, step),
          tint: _lerp(-0.02, 0.02, step),
          aura: index % 4 == 0 ? _lerp(0.05, 0.12, step) : 0.0,
          auraColor: const Color(0xFFF8F7F2),
          grain: _lerp(0.01, 0.06, step),
          overlayColor: const Color(0x0DFFFFFF),
          vignette: _lerp(0.03, 0.09, step),
        );
      },
    ),
    ..._buildPack(
      categoryId: 'portrait',
      categoryEn: 'Portrait',
      categoryAr: 'بورتريه',
      badgeEn: 'Portrait',
      badgeAr: 'بورتريه',
      taglineEn: 'Skin-first glow with gentle subject lift.',
      taglineAr: 'تركيز لطيف على البشرة مع هالة ناعمة.',
      icon: Icons.face_retouching_natural_rounded,
      accent: const Color(0xFFFFC78B),
      featuredIndices: const {1, 4, 9},
      namesEn: const [
        'Skin Whisper',
        'Rose Portrait',
        'Golden Muse',
        'Soft Halo',
        'Pearl Face',
        'Honey Studio',
        'Velvet Skin',
        'Daylight Bride',
        'Aura Bloom',
        'Natural Luxe',
      ],
      namesAr: const [
        'همس البشرة',
        'بورتريه وردي',
        'ملهمة ذهبية',
        'هالة ناعمة',
        'وجه لؤلؤي',
        'استوديو العسل',
        'بشرة مخملية',
        'عروس النهار',
        'ازدهار الهالة',
        'فخامة طبيعية',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.04, 1.12, step),
          saturation: _lerp(1.04, 1.14, step),
          exposure: _lerp(0.0, 0.06, step),
          brightness: _lerp(0.0, 0.04, step),
          warmth: _lerp(0.08, 0.18, step),
          tint:
              index.isEven ? _lerp(0.0, 0.03, step) : _lerp(-0.01, 0.02, step),
          blur: _lerp(1.2, 3.4, step),
          aura: _lerp(0.18, 0.42, step),
          auraColor: index % 3 == 0
              ? const Color(0xFFFFD6A3)
              : const Color(0xFFFFF1D9),
          grain: _lerp(0.01, 0.06, step),
          overlayColor:
              index.isEven ? const Color(0x14FFB06B) : const Color(0x10FFF0DB),
          vignette: _lerp(0.06, 0.14, step),
          lightLeakIndex: index % 5 == 0 ? 1 : 0,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'neon',
      categoryEn: 'Neon',
      categoryAr: 'نيون',
      badgeEn: 'Pulse',
      badgeAr: 'نبض',
      taglineEn: 'Electric color, glow bloom, and nightlife energy.',
      taglineAr: 'ألوان كهربائية وتوهج حيوي وطاقة ليلية.',
      icon: Icons.bolt_rounded,
      accent: const Color(0xFF54E8FF),
      featuredIndices: const {0, 3, 6},
      namesEn: const [
        'Neon Pulse',
        'Cyan Rush',
        'Pink Static',
        'Laser Pop',
        'Future Alley',
        'Digital Club',
        'Turbo Night',
        'Electric Rain',
        'Holo Drift',
        'Signal Glow',
      ],
      namesAr: const [
        'نبض النيون',
        'اندفاع سياني',
        'ستاتيك وردي',
        'بوب ليزري',
        'زقاق مستقبلي',
        'نادي رقمي',
        'ليل توربو',
        'مطر كهربائي',
        'انجراف هولو',
        'توهج الإشارة',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.12, 1.24, step),
          saturation: _lerp(1.18, 1.34, step),
          exposure: _lerp(-0.01, 0.05, step),
          brightness: _lerp(-0.02, 0.02, step),
          warmth: _lerp(-0.10, 0.02, step),
          tint: _lerp(0.04, 0.12, step),
          blur: _lerp(2.0, 6.4, step),
          aura: _lerp(0.24, 0.58, step),
          auraColor:
              index.isEven ? const Color(0xFFFF56D8) : const Color(0xFF52E7FF),
          grain: _lerp(0.02, 0.10, step),
          scanlines: _lerp(0.04, 0.12, step),
          glitch: _lerp(0.10, 0.40, step),
          overlayColor:
              index.isEven ? const Color(0x1500D7FF) : const Color(0x16FF52D9),
          vignette: _lerp(0.06, 0.16, step),
          lightLeakIndex: 2,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'vintage',
      categoryEn: 'Vintage',
      categoryAr: 'فينتج',
      badgeEn: 'Archive',
      badgeAr: 'أرشيف',
      taglineEn: 'Archive grain, warm fade, and analog mood.',
      taglineAr: 'حبوب أرشيفية ودفء باهت ولمسة أنالوج.',
      icon: Icons.camera_roll_rounded,
      accent: const Color(0xFFFFBE7A),
      featuredIndices: const {0, 5, 9},
      namesEn: const [
        'Analog Gold',
        'Sepia Motel',
        'Dust Film',
        'Retro Diary',
        'Cassette Sun',
        'Archive 82',
        'Grain Story',
        'Warm Memory',
        'Classic Fade',
        'Old Cinema',
      ],
      namesAr: const [
        'ذهب أنالوج',
        'موتيل سيبيا',
        'غبار الفيلم',
        'يوميات ريترو',
        'شمس الكاسيت',
        'أرشيف 82',
        'قصة الحبوب',
        'ذاكرة دافئة',
        'بهتان كلاسيكي',
        'سينما قديمة',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.02, 1.12, step),
          saturation: _lerp(0.88, 1.08, step),
          exposure: _lerp(-0.02, 0.04, step),
          brightness: _lerp(-0.01, 0.03, step),
          warmth: _lerp(0.08, 0.18, step),
          blur: index.isEven ? _lerp(0.0, 1.2, step) : 0.0,
          grain: _lerp(0.14, 0.32, step),
          scanlines: _lerp(0.08, 0.24, step),
          overlayColor:
              index.isEven ? const Color(0x18FFB06B) : const Color(0x14D98B4B),
          showDateStamp: index % 4 == 0,
          vignette: _lerp(0.10, 0.20, step),
          lightLeakIndex: 1,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'street',
      categoryEn: 'Street',
      categoryAr: 'ستريت',
      badgeEn: 'Urban',
      badgeAr: 'حضري',
      taglineEn: 'Punchy detail with urban motion and texture.',
      taglineAr: 'حدة حضرية مع حركة واضحة وخامة قوية.',
      icon: Icons.flash_on_rounded,
      accent: const Color(0xFFFFD166),
      featuredIndices: const {2, 5, 8},
      namesEn: const [
        'Asphalt Pop',
        'Night Sprint',
        'Graffiti Flash',
        'Rebel Frame',
        'City Hustle',
        'Metro Edge',
        'Flash Crowd',
        'Concrete Noise',
        'Rooftop Heat',
        'Motion District',
      ],
      namesAr: const [
        'بوب الأسفلت',
        'اندفاع الليل',
        'فلاش الغرافيتي',
        'إطار متمرّد',
        'صخب المدينة',
        'حافة المترو',
        'حشد الفلاش',
        'ضوضاء الخرسانة',
        'حرارة السطح',
        'حي الحركة',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.14, 1.26, step),
          saturation: _lerp(1.08, 1.18, step),
          exposure: _lerp(-0.01, 0.04, step),
          brightness: _lerp(-0.01, 0.02, step),
          warmth:
              index.isEven ? _lerp(-0.04, 0.05, step) : _lerp(0.0, 0.04, step),
          blur: _lerp(0.0, 1.0, step),
          aura: index % 3 == 0 ? _lerp(0.08, 0.16, step) : 0.0,
          auraColor: const Color(0xFF90F5FF),
          grain: _lerp(0.08, 0.18, step),
          scanlines: _lerp(0.06, 0.16, step),
          glitch: _lerp(0.04, 0.26, step),
          overlayColor: const Color(0x0DFFFFFF),
          cinemaMode: index.isOdd,
          vignette: _lerp(0.12, 0.22, step),
          lightLeakIndex: index % 2 == 0 ? 1 : 0,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'mono',
      categoryEn: 'Mono',
      categoryAr: 'أحادي',
      badgeEn: 'Mono',
      badgeAr: 'أحادي',
      taglineEn: 'Monochrome depth with crisp premium contrast.',
      taglineAr: 'عمق أحادي مع تباين فاخر ونظيف.',
      icon: Icons.filter_b_and_w_rounded,
      accent: const Color(0xFFE7EEF6),
      featuredIndices: const {0, 6, 9},
      namesEn: const [
        'Silver Mono',
        'Carbon Story',
        'Noir Dust',
        'Fade Silver',
        'Classic Mono',
        'Monochrome Club',
        'White Collar',
        'Dark Ink',
        'Soft Graphite',
        'Black Room',
      ],
      namesAr: const [
        'أحادي فضي',
        'قصة كربونية',
        'غبار نوار',
        'فضي باهت',
        'أحادي كلاسيكي',
        'نادي أحادي',
        'ياقة بيضاء',
        'حبر داكن',
        'غرافيت ناعم',
        'الغرفة السوداء',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.16, 1.28, step),
          saturation: _lerp(0.08, 0.24, step),
          exposure: _lerp(-0.03, 0.05, step),
          brightness: _lerp(-0.02, 0.03, step),
          tint: _lerp(-0.02, 0.02, step),
          grain: _lerp(0.06, 0.18, step),
          scanlines: index % 4 == 0 ? 0.08 : 0.0,
          colorPop: index % 3 == 0,
          overlayColor:
              index.isEven ? const Color(0x0DFFFFFF) : const Color(0x12000000),
          cinemaMode: index.isOdd,
          vignette: _lerp(0.14, 0.24, step),
        );
      },
    ),
    ..._buildPack(
      categoryId: 'dreamy',
      categoryEn: 'Dreamy',
      categoryAr: 'حالم',
      badgeEn: 'Aura',
      badgeAr: 'هالة',
      taglineEn: 'Soft focus glow with airy pastel diffusion.',
      taglineAr: 'ضبابية حالمة وتوهج باستيل خفيف.',
      icon: Icons.cloud_rounded,
      accent: const Color(0xFFE7AFFF),
      featuredIndices: const {1, 4, 7},
      namesEn: const [
        'Cloud Kiss',
        'Lavender Sky',
        'Cotton Glow',
        'Dream Motel',
        'Pastel Float',
        'Moon Candy',
        'Iris Fog',
        'Soft Orbit',
        'Bloom Aura',
        'Lullaby Light',
      ],
      namesAr: const [
        'قبلة الغيم',
        'سماء لافندر',
        'توهج قطني',
        'موتيل حالم',
        'عوم باستيل',
        'حلوى القمر',
        'ضباب آيرس',
        'مدار ناعم',
        'هالة مزهرة',
        'ضوء التهويدة',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.02, 1.10, step),
          saturation: _lerp(1.08, 1.18, step),
          exposure: _lerp(0.0, 0.05, step),
          brightness: _lerp(0.0, 0.03, step),
          warmth: _lerp(0.02, 0.10, step),
          tint: _lerp(0.02, 0.08, step),
          blur: _lerp(1.6, 4.8, step),
          aura: _lerp(0.18, 0.42, step),
          auraColor:
              index.isEven ? const Color(0xFFE8B8FF) : const Color(0xFFFFC9E4),
          grain: _lerp(0.02, 0.08, step),
          overlayColor:
              index.isEven ? const Color(0x12EAB7FF) : const Color(0x14FFB8D7),
          vignette: _lerp(0.06, 0.14, step),
        );
      },
    ),
    ..._buildPack(
      categoryId: 'luxury',
      categoryEn: 'Luxury',
      categoryAr: 'فاخر',
      badgeEn: 'Luxe',
      badgeAr: 'فاخر',
      taglineEn: 'Refined chrome contrast with luxe warmth.',
      taglineAr: 'تباين مصقول بلمسة فاخرة ودفء راقٍ.',
      icon: Icons.diamond_rounded,
      accent: const Color(0xFFFFD37E),
      featuredIndices: const {0, 3, 9},
      namesEn: const [
        'Champagne Cut',
        'Gold Label',
        'Diamond Tone',
        'Silk Night',
        'Pearl Gold',
        'Platinum Air',
        'Velvet Class',
        'Royal Clean',
        'Premium Room',
        'Black Tie',
      ],
      namesAr: const [
        'قطع الشمبانيا',
        'الملصق الذهبي',
        'نغمة الألماس',
        'ليلة حريرية',
        'ذهب لؤلؤي',
        'هواء بلاتيني',
        'فئة مخملية',
        'نظافة ملكية',
        'الغرفة الممتازة',
        'ربطة سوداء',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.10, 1.20, step),
          saturation: _lerp(1.04, 1.12, step),
          exposure: _lerp(0.01, 0.06, step),
          brightness: _lerp(-0.01, 0.02, step),
          warmth: _lerp(0.04, 0.12, step),
          tint: _lerp(-0.01, 0.02, step),
          aura: index % 3 == 0 ? _lerp(0.04, 0.12, step) : 0.0,
          auraColor: const Color(0xFFFFE2A3),
          grain: _lerp(0.0, 0.05, step),
          overlayColor:
              index.isEven ? const Color(0x12FFE1A3) : const Color(0x0DFFFFFF),
          vignette: _lerp(0.06, 0.12, step),
        );
      },
    ),
    ..._buildPack(
      categoryId: 'summer',
      categoryEn: 'Summer',
      categoryAr: 'صيفي',
      badgeEn: 'Solar',
      badgeAr: 'شمسي',
      taglineEn: 'Sun-kissed warmth with clean travel color.',
      taglineAr: 'دفء شمسي مع ألوان سفر نقية.',
      icon: Icons.wb_sunny_rounded,
      accent: const Color(0xFFFFA95E),
      featuredIndices: const {0, 4, 7},
      namesEn: const [
        'Sunset Wave',
        'Peach Heat',
        'Holiday Skin',
        'Palm Glow',
        'Tropic Dust',
        'Beach Club',
        'Solar Kiss',
        'Warm Tide',
        'Coral Light',
        'Golden Hour',
      ],
      namesAr: const [
        'موجة الغروب',
        'حرارة الخوخ',
        'بشرة العطلة',
        'توهج النخيل',
        'غبار استوائي',
        'نادي الشاطئ',
        'قبلة شمسية',
        'مد دافئ',
        'ضوء المرجان',
        'الساعة الذهبية',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.04, 1.14, step),
          saturation: _lerp(1.08, 1.20, step),
          exposure: _lerp(0.02, 0.10, step),
          brightness: _lerp(0.01, 0.05, step),
          warmth: _lerp(0.12, 0.24, step),
          tint: _lerp(-0.01, 0.04, step),
          blur: _lerp(0.4, 1.8, step),
          aura: _lerp(0.08, 0.20, step),
          auraColor:
              index.isEven ? const Color(0xFFFFC46B) : const Color(0xFFFF8F70),
          grain: _lerp(0.01, 0.08, step),
          overlayColor:
              index.isEven ? const Color(0x16FFB56B) : const Color(0x14FF7E6B),
          vignette: _lerp(0.04, 0.12, step),
          lightLeakIndex: 1,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'creator',
      categoryEn: 'Creator',
      categoryAr: 'صانع محتوى',
      badgeEn: 'Trending',
      badgeAr: 'ترند',
      taglineEn:
          'Polished creator color with airy skin, soft highlights, and premium social clarity.',
      taglineAr:
          'ألوان صناع محتوى مصقولة مع بشرة مشرقة ولمعان ناعم ولمسة اجتماعية احترافية.',
      icon: Icons.smart_display_rounded,
      accent: const Color(0xFFFFAFD4),
      featuredIndices: const {0, 4, 8},
      namesEn: const [
        'GRWM Glow',
        'Mirror Check',
        'Soft Launch',
        'Daily Edit',
        'Clean Feed',
        'Story Hour',
        'Creator Air',
        'Vlog Polish',
        'Cloud Selfie',
        'Weekend Reel',
      ],
      namesAr: const [
        'توهج الجاهزية',
        'لقطة المرآة',
        'إطلاق ناعم',
        'إيديت يومي',
        'خلاصة نظيفة',
        'لحظة ستوري',
        'هواء المحتوى',
        'تلميع الفلوق',
        'سيلفي سحابي',
        'ريل الويكند',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.04, 1.14, step),
          saturation: _lerp(1.02, 1.14, step),
          exposure: _lerp(0.01, 0.07, step),
          brightness: _lerp(0.0, 0.04, step),
          warmth:
              index.isEven ? _lerp(0.01, 0.09, step) : _lerp(-0.01, 0.05, step),
          tint: _lerp(-0.01, 0.03, step),
          blur: index % 4 == 0 ? _lerp(0.2, 1.0, step) : _lerp(0.0, 0.5, step),
          aura: index % 3 == 0
              ? _lerp(0.05, 0.14, step)
              : _lerp(0.02, 0.08, step),
          auraColor:
              index.isEven ? const Color(0xFFFFE4F1) : const Color(0xFFE7FFF7),
          grain: _lerp(0.0, 0.04, step),
          overlayColor:
              index.isEven ? const Color(0x10FFF3F8) : const Color(0x0CF6FFF9),
          vignette: _lerp(0.02, 0.08, step),
          prismOverlay: index % 4 == 0 ? _lerp(0.03, 0.08, step) : 0.0,
          dustOverlay: index % 5 == 0 ? _lerp(0.02, 0.06, step) : 0.0,
          colorPop: index % 3 == 0,
          showDateStamp: index % 5 == 0,
          lightLeakIndex: index % 4 == 0 ? 1 : 0,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'flash',
      categoryEn: 'Flash',
      categoryAr: 'فلاش',
      badgeEn: 'Runway',
      badgeAr: 'فاشن',
      taglineEn:
          'Direct-flash contrast with bold skin tone, reflective highlights, and nightlife attitude.',
      taglineAr:
          'تباين فلاش مباشر مع طابع جريء ولمعان منعكس وطاقة ليلية عصرية.',
      icon: Icons.flash_on_rounded,
      accent: const Color(0xFFF5F3FF),
      featuredIndices: const {1, 5, 8},
      namesEn: const [
        'Afterparty Flash',
        'Night Flash',
        'Mirror Blitz',
        'Flash Diary',
        'Backroom Pop',
        'Club Portrait',
        'Silver Flash',
        'Late Check',
        'Studio Flash',
        'Bold Frame',
      ],
      namesAr: const [
        'فلاش السهرة',
        'فلاش الليل',
        'وميض المرآة',
        'مذكرات الفلاش',
        'بريق الكواليس',
        'بورتريه النادي',
        'فلاش فضي',
        'لقطة متأخرة',
        'فلاش الاستوديو',
        'إطار جريء',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.10, 1.24, step),
          saturation: _lerp(0.94, 1.08, step),
          exposure: _lerp(-0.04, 0.03, step),
          brightness: _lerp(-0.04, 0.02, step),
          warmth: index < 5 ? _lerp(-0.04, 0.03, step) : _lerp(0.0, 0.06, step),
          tint: _lerp(0.02, 0.08, step),
          blur: index % 4 == 0 ? _lerp(0.2, 1.0, step) : 0.0,
          aura: index % 3 == 0 ? _lerp(0.02, 0.08, step) : 0.0,
          auraColor:
              index.isEven ? const Color(0xFFF6F4FF) : const Color(0xFFE6F7FF),
          grain: _lerp(0.04, 0.12, step),
          scanlines: index % 4 == 0 ? 0.04 : 0.0,
          overlayColor:
              index.isEven ? const Color(0x14000000) : const Color(0x10F5EFFF),
          vignette: _lerp(0.08, 0.16, step),
          prismOverlay: index % 3 == 1 ? _lerp(0.03, 0.10, step) : 0.0,
          dustOverlay: index.isEven ? _lerp(0.02, 0.08, step) : 0.0,
          colorPop: index % 4 == 1,
          showDateStamp: index % 3 == 0,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'product',
      categoryEn: 'Product',
      categoryAr: 'منتجات',
      badgeEn: 'Commerce',
      badgeAr: 'تجاري',
      taglineEn:
          'Commercial-ready polish with premium contrast, clean color separation, and launch-day shine.',
      taglineAr:
          'لمسة تجارية جاهزة للعرض مع تباين مصقول وفصل ألوان نظيف ولمعان احترافي.',
      icon: Icons.inventory_2_rounded,
      accent: const Color(0xFF9EE7FF),
      featuredIndices: const {0, 3, 7},
      namesEn: const [
        'Hero Shelf',
        'Brand Pop',
        'Clean Launch',
        'Studio Cart',
        'Premium Drop',
        'Silk Surface',
        'Retail Shine',
        'Packshot Pro',
        'Soft Spec',
        'Launch Day',
      ],
      namesAr: const [
        'واجهة المنتج',
        'بريق العلامة',
        'إطلاق نظيف',
        'استوديو العرض',
        'دفعة فاخرة',
        'سطح حريري',
        'لمعان البيع',
        'صورة المنتج',
        'نعومة التفاصيل',
        'يوم الإطلاق',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.08, 1.18, step),
          saturation: _lerp(1.02, 1.16, step),
          exposure: _lerp(0.0, 0.08, step),
          brightness: _lerp(-0.01, 0.03, step),
          warmth:
              index.isEven ? _lerp(-0.02, 0.04, step) : _lerp(0.01, 0.08, step),
          tint: _lerp(-0.02, 0.02, step),
          blur: _lerp(0.0, 0.4, step),
          aura: index % 5 == 0 ? _lerp(0.02, 0.06, step) : 0.0,
          auraColor:
              index.isEven ? const Color(0xFFF7FDFF) : const Color(0xFFFFF5E8),
          grain: _lerp(0.0, 0.03, step),
          overlayColor:
              index.isEven ? const Color(0x0BFFFFFF) : const Color(0x0AFFF4E0),
          vignette: _lerp(0.02, 0.08, step),
          prismOverlay: index % 4 == 0 ? _lerp(0.02, 0.05, step) : 0.0,
          colorPop: index.isEven,
        );
      },
    ),
    ..._buildPack(
      categoryId: 'travel',
      categoryEn: 'Travel',
      categoryAr: 'سفر',
      badgeEn: 'Explorer',
      badgeAr: 'رحلة',
      taglineEn:
          'Creator-grade travel color with postcard warmth, crisp atmosphere, and editorial city glow.',
      taglineAr:
          'ألوان سفر عصرية بدفء بطاقات بريدية ووضوح جميل ولمسة مدينة تحريرية.',
      icon: Icons.explore_rounded,
      accent: const Color(0xFF63D7FF),
      featuredIndices: const {0, 4, 9},
      namesEn: const [
        'Passport Blue',
        'City Postcard',
        'Nomad Sun',
        'Weekend Flight',
        'Rooftop Guide',
        'Golden Transit',
        'Open Road',
        'Atlas Glow',
        'Boarding Pass',
        'Cafe Stop',
      ],
      namesAr: const [
        'أزرق الجواز',
        'بطاقة المدينة',
        'شمس الرحالة',
        'رحلة الويكند',
        'سطح المدينة',
        'عبور ذهبي',
        'الطريق المفتوح',
        'توهج الأطلس',
        'بطاقة الصعود',
        'وقفة المقهى',
      ],
      buildRecipe: (index) {
        final step = _step(index);
        return FilterParams(
          contrast: _lerp(1.05, 1.16, step),
          saturation: _lerp(1.08, 1.22, step),
          exposure: _lerp(0.01, 0.08, step),
          brightness: _lerp(0.0, 0.04, step),
          warmth: _lerp(0.04, 0.16, step),
          tint: _lerp(-0.02, 0.04, step),
          blur: index % 5 == 0 ? _lerp(0.6, 1.4, step) : _lerp(0.2, 0.8, step),
          aura: _lerp(0.04, 0.14, step),
          auraColor:
              index.isEven ? const Color(0xFFFFC98A) : const Color(0xFF7EE1FF),
          grain: _lerp(0.01, 0.08, step),
          overlayColor:
              index.isEven ? const Color(0x12FFB06B) : const Color(0x1000D7FF),
          vignette: _lerp(0.04, 0.12, step),
          prismOverlay: index % 3 == 0 ? _lerp(0.03, 0.10, step) : 0.0,
          dustOverlay: index % 4 == 0 ? _lerp(0.03, 0.08, step) : 0.0,
          colorPop: index % 4 == 1,
          showDateStamp: index % 5 == 0,
          lightLeakIndex: index % 3 == 0 ? 1 : 0,
        );
      },
    ),
  ];
}

List<FilterStudioStylePreset> _buildPack({
  required String categoryId,
  required String categoryEn,
  required String categoryAr,
  required String badgeEn,
  required String badgeAr,
  required String taglineEn,
  required String taglineAr,
  required IconData icon,
  required Color accent,
  required Set<int> featuredIndices,
  required List<String> namesEn,
  required List<String> namesAr,
  required FilterParams Function(int index) buildRecipe,
}) {
  return List<FilterStudioStylePreset>.generate(namesEn.length, (index) {
    final id = '${categoryId}_${index + 1}';
    return FilterStudioStylePreset(
      id: id,
      categoryId: categoryId,
      categoryEn: categoryEn,
      categoryAr: categoryAr,
      badgeEn: badgeEn,
      badgeAr: badgeAr,
      nameEn: namesEn[index],
      nameAr: namesAr[index],
      taglineEn: taglineEn,
      taglineAr: taglineAr,
      icon: icon,
      accent: accent,
      featured: featuredIndices.contains(index),
      recipe: buildRecipe(index),
    );
  });
}

double _step(int index) => index / 9;

double _lerp(double from, double to, double step) =>
    from + ((to - from) * step);
